meter:
  device: /dev/ttyUSB0
  baud: 9600
  data_bits: 7
  stop_bits: 1
  parity: even   # none | even | odd
  update_interval: 5

modbus:
  tcp:
    listen: 0.0.0.0
    port: 502
  rtu:
    device: /dev/ttyUSB1
    baud: 9600
  slave_id: 1
  indication_timeout:
    sec: 10
    usec: 0
  use_float_model: false
      
mqtt:
  broker: localhost
  port: 1883
  topic: smartmeter-gateway
  #user: mqtt
  #password: "your-secret-password"
  queue_size: 100
  reconnect_delay:
    min: 2
    max: 64
    exponential: true
  
logger:
  level: info     # global default: off | error | warn | info | debug | trace
  modules:
    main: info
    meter: debug
    modbus: info
    mqtt: info
