meter:
  device: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB65FI6I-if00-port0
  baud: 9600
  data_bits: 7
  stop_bits: 1
  parity: even   # none | even | odd
  update_interval: 5
  reconnect_delay:
    min: 5
    max: 320
    exponential: true

modbus:
  tcp:
    listen: 0.0.0.0
    port: 502
  rtu:
    device: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AC009Y6C-if00-port0
    baud: 9600
  slave_id: 1
  indication_timeout:
    sec: 10
    usec: 0
  use_float_model: false
      
mqtt:
  broker: 192.168.6.80
  port: 1883
  topic: smartmeter-gateway
  #user: mqtt
  #password: "your secret password"
  queue_size: 100
  reconnect_delay:
    min: 2
    max: 64
    exponential: true
  
logger:
  level: info     # global default: off | error | warn | info | debug | trace
  modules:
    main: info
    meter: debug
    modbus: info
    mqtt: info
