modbus:
  tcp:
    listen: 0.0.0.0
    port: 502
  rtu:
    device: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AC009Y6C-if00-port0
    baud: 9600
  slave_id: 1
  indication_timeout:
    sec: 10
    usec: 0
  use_float_model: false
      
mqtt:
  broker: localhost
  port: 1883
  topic: smartmeter-gateway
  #user: mqtt
  #password: "your-secret-password"
  queue_size: 100
  reconnect_delay:
    min: 2
    max: 64
    exponential: true
  
logger:
  level: info     # global default: off | error | warn | info | debug | trace
  modules:
    main: info
    modbus: info
    mqtt: debug
